name: eng2man
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - comm=0.2.2
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - krb5=1.21.2
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.2
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libzlib=1.2.13
  - matplotlib-inline=0.1.7
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - openssl=3.3.0
  - packaging=24.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.1
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.12.3
  - python-dateutil=2.9.0
  - python_abi=3.12
  - pyzmq=26.0.2
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - attrs==23.2.0
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - confection==0.1.4
      - contourpy==1.2.1
      - cycler==0.12.1
      - cymem==2.0.8
      - datasets==2.19.0
      - dill==0.3.8
      - en-core-web-sm==3.7.1
      - filelock==3.14.0
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - huggingface-hub==0.23.0
      - idna==3.7
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - langcodes==3.4.0
      - language-data==1.2.0
      - marisa-trie==1.1.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - networkx==3.3
      - numpy==1.26.4
      - pandas==2.2.2
      - pillow==10.3.0
      - preshed==3.0.9
      - pyarrow==16.0.0
      - pyarrow-hotfix==0.6
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pyparsing==3.1.2
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - smart-open==6.4.0
      - spacy==3.7.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spacy-pkuseg==0.0.33
      - srsly==2.4.8
      - sympy==1.12
      - thinc==8.2.3
      - threadpoolctl==3.5.0
      - torch==2.3.0
      - torchtext==0.18.0
      - tqdm==4.66.4
      - typer==0.9.4
      - tzdata==2024.1
      - urllib3==2.2.1
      - wasabi==1.1.2
      - weasel==0.3.4
      - xxhash==3.4.1
      - yarl==1.9.4
      - zh-core-web-sm==3.7.0
